name: Automatisation des tests
on: push
jobs:
  Compilation:
    runs-on: ubuntu-latest
    steps:
      - name: Compilation
        run: |
          last_directory=$(basename ${{ runner.workspace }})
          git clone https://github.com/${{ github.repository }}.git
          cd ./$last_directory
          mkdir build
          cd build
          cmake ..
          make
          make test
  Tests:
    needs: Compilation
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test: [Add, Sub, Mul, Div]
    steps:
      - name: Test_${{ matrix.test }} 
        run: |
          last_directory=$(basename ${{ runner.workspace }})
          git clone https://github.com/${{ github.repository }}.git
          cd ./$last_directory
          mkdir build
          cd build
          cmake ..
          make
          func=$(echo "${{ matrix.test }}" | tr '[:upper:]' '[:lower:]')
          ./src/calculator $func 10 5
      - name: Test_Car
        run: |
          last_directory=$(basename ${{ runner.workspace }})
          cd ./$last_directory/build
          ./src/calculator car 5
  Deploy:
    needs: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo "Déploiement de la solution"
