name: Automatisation des tests
on: push
jobs:
  Compilation:
    runs-on: ubuntu-latest
    steps:
      - name: Compilation
        run: |
          last_directory=$(basename ${{ runner.workspace }})
          git clone https://github.com/${{ github.repository }}.git
          cd ./$last_directory
          mkdir build
          cd build
          cmake ..
          make
          make test
  Tests:
    needs: Compilation
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test: [Add, Sub, Mul, Div]
        test2: [add, sub, mul, div]
    steps:
      - name: Test_${{ matrix.test }} 
        run: |
          last_directory=$(basename ${{ runner.workspace }})
          git clone https://github.com/${{ github.repository }}.git
          cd ./$last_directory
          mkdir build
          cd build
          cmake ..
          make
          ./src/calculator ${{ matrix.test2 }} 10 5
  Deploy:
    needs: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo "Déploiement de la solution"
